[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["TulioAA <tulioalmeida67@gmail.com>"]
license = "MIT"
packages = [
    { include = "app" }
]

[tool.poetry.dependencies]
python = ">=3.12"
fastapi = ">=0.141.1,<0.142.0"
uvicorn = ">=0.52.1,<0.53.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=9.1.1,<10.0.0"
httpx = ">=0.28.1,<0.29.0"
ruff = ">=0.16.2,<0.17.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
